server:
  port: 8821
spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    # Nacos配置
    nacos:
      server-addr: 127.0.0.1:8848
#      discovery:
#        enabled: true
      config:
        namespace: ${spring.profiles.active:public}
#        enabled: true
        auto-refresh: true
        enable-remote-sync-config: true
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      web-context-unify: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

#logging:
#  level:
#    com.alibaba.cloud.nacos: DEBUG
#    org.springframework.cloud: DEBUG

---
spring:
  config:
    import:
      - nacos:database.yaml?group=user-service
      - nacos:greeting.yaml?group=user-service
    activate:
      on-profile: dev

#nocas中配置数据库连接：data_id=database.yaml; group=user-service
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ms_user?characterEncoding=utf-8&useSSL=FALSE&allowPublicKeyRetrieval=true
#    username: test
#    password: 123456  # 请根据实际修改
#    driver-class-name: com.mysql.cj.jdbc.Driver
