server:
  port: 8083
spring:
  application:
    name: gateway-service
  config:
    import: optional:nacos

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: true

    gateway:
      routes:
        - id: department-route
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      # 自定义限流返回（可选）
#      default-filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: "#{@remoteAddrKeyResolver}"
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 2
# 自定义白名单配置（用于JWT鉴权）
custom-gateway:
  whitelist:
    paths:
      - /auth/login
      - /auth/register
      - /swagger-ui/**
      - /v3/api-docs/**