-- 用户表
DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    age INT
);

-- 用户操作日志表
DROP TABLE IF EXISTS user_log;
CREATE TABLE user_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    action VARCHAR(100),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);